
POST  http://localhost:3000/search-posts
Content-Type: application/json

{
    "tag": "sky"
}

# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#      "fullname": "Test1",
#      "email": "test3@gmail.com",
#      "password": "Test123"
# }


# POST http://localhost:3000/signin 
# Content-Type: application/json

# {
#     "email": "lostofspace5@test1.com",
#     "password": "Test1"
# }


# POST http://localhost:3000/create-post
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjE1ZWE0ZjFhMDg4Yzk5Zjg2ZmFiMiIsImlhdCI6MTczNDQzNDQ2OH0.TyHLuF7mBUv97H3iAgSagej3D3D1a2ZXCFEfJ4PtdDA

# {
#     "title": "Test Title2",
#     "banner": "https://test.com//url",
#     "des": "A short desc",
#     "content": {
#         "blocks": [1, 2]
#     },
#     "tags": ["tag1", "Tag 2"]
# }